[package]
name = "hypergolic_game_engine"
version = "0.1.0"
authors = ["vince <vince.siu4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luminance = "0.39"
luminance-glfw = "0.12"
